with seed as (
  select *
  from jsonb_to_recordset(
    $json$
    [
      {"company_name":"McCain Foods","website_url":"https://www.mccain.com","contact_url":"https://www.mccain.com/contact-us/","products":["Frozen fries","Potato products","Frozen meals"],"notes":"Global leader in potato processing."},
      {"company_name":"Saputo Inc.","website_url":"https://www.saputo.com","contact_url":"https://www.saputo.com/en/contact-us","products":[],"notes":"Major multinational dairy processor."},
      {"company_name":"StackTeck Systems Ltd.","website_url":"https://www.stackteck.com","contact_url":"https://stackteck.com/contact/","products":[],"notes":"High-volume molding technology provider."},
      {"company_name":"Canada Goose","website_url":"https://www.canadagoose.com","contact_url":"https://www.canadagoose.com/ca/en/contact-us/","products":[],"notes":"High-end domestic apparel production."},
      {"company_name":"West Fraser","website_url":"https://www.westfraser.com","contact_url":"https://www.westfraser.com/contact","products":[],"notes":"Largest lumber producer in North America."},
      {"company_name":"Bothwell Cheese","website_url":"https://www.bothwellcheese.com","contact_url":"https://www.bothwellcheese.com/contact-us/","products":["Artisanal cheese"],"notes":"Premium Manitoba dairy manufacturer."},
      {"company_name":"ABC Technologies","website_url":"https://www.abctechnologies.com","contact_url":"https://abctechnologies.com/contact/","products":["Automotive plastics"],"notes":"Specializes in complex automotive assemblies."},
      {"company_name":"Stanfield's Ltd.","website_url":"https://www.stanfields.com","contact_url":"https://www.stanfields.com/pages/contact-us","products":[],"notes":"Historic textile manufacturer in Nova Scotia."},
      {"company_name":"Canfor","website_url":"https://www.canfor.com","contact_url":"https://www.canfor.com/contact","products":[],"notes":"Sustainable forestry and green energy leader."},
      {"company_name":"ID Technology","website_url":"https://www.idtechnology.com","contact_url":"https://www.idtechnology.com/contact-us/","products":["Labeling systems"],"notes":"Integrated coding and marking solutions."},
      {"company_name":"Dare Foods","website_url":"https://www.darefoods.com","contact_url":"https://www.darefoods.com/ca_en/contact","products":["Cookies","Crackers"],"notes":"Family-owned Canadian snack giant."},
      {"company_name":"Custom Plastics International","website_url":"https://www.customplastics.ca","contact_url":"https://customplastics.ca/contact-us/","products":["Precision thermoplastics"],"notes":"Specialized industrial parts manufacturer."},
      {"company_name":"Cansew Inc.","website_url":"https://www.cansew.ca","contact_url":"https://cansew.ca/contact/","products":[],"notes":"Major supplier to the garment industry."},
      {"company_name":"Interfor","website_url":"https://www.interfor.com","contact_url":"https://www.interfor.com/contact","products":[],"notes":"Diverse global sawmill operator."},
      {"company_name":"Lorpon Labels","website_url":"https://www.lorponlabels.com","contact_url":"https://www.lorponlabels.com/contact/","products":[],"notes":"Short-run digital label specialist."},
      {"company_name":"Lassonde Industries","website_url":"https://www.lassonde.com","contact_url":"https://www.lassonde.com/en/contact-us/","products":[],"notes":"Diverse food and beverage portfolio."},
      {"company_name":"PH Molds Limited","website_url":"https://www.phmolds.com","contact_url":"https://www.phmolds.com/contact/","products":["Complex plastic parts"],"notes":"Optimized mold design and production."},
      {"company_name":"Kendor Textiles","website_url":"https://www.kendortextiles.com","contact_url":"https://kendortextiles.com/pages/contact-us","products":[],"notes":"Wholesaler of performance textiles."},
      {"company_name":"Resolute Forest Products","website_url":"https://www.resolutefp.com","contact_url":"https://www.resolutefp.com/Contact_Us/","products":[],"notes":"Integrated forest products manufacturer."},
      {"company_name":"Glenmore Custom Print","website_url":"https://www.glenmorecustomprint.com","contact_url":"https://glenmorecustomprint.com/contact/","products":["Custom packaging"],"notes":"Full-service printer based in Richmond."},
      {"company_name":"Chapman's Ice Cream","website_url":"https://www.chapmans.ca","contact_url":"https://www.chapmans.ca/contact-us/","products":["Ice cream"],"notes":"Canada's largest independent manufacturer."},
      {"company_name":"Baytech Plastics","website_url":"https://www.baytechplastics.com","contact_url":"https://www.baytechplastics.com/contact/","products":["Electronic enclosures"],"notes":"Full-cycle custom injection molding."},
      {"company_name":"Naked & Famous Denim","website_url":"https://www.nakedandfamousdenim.com","contact_url":"https://www.nakedandfamousdenim.com/en/contact","products":[],"notes":"Premium apparel made in Montreal."},
      {"company_name":"Western Forest Products","website_url":"https://www.westernforest.com","contact_url":"https://www.westernforest.com/contact-us/","products":["Cedar siding"],"notes":"Specializes in coastal wood species."},
      {"company_name":"Altro Labels","website_url":"https://www.altrolabels.com","contact_url":"https://altrolabels.com/contact-us/","products":[],"notes":"Innovative beverage labeling specialist."},
      {"company_name":"Maple Leaf Foods","website_url":"https://www.mapleleaffoods.com","contact_url":"https://www.mapleleaffoods.com/contact-us/","products":["Prepared proteins"],"notes":"Sustainability-focused protein company."},
      {"company_name":"Precision Injection Molding Inc.","website_url":"https://www.precisionmolding.com","contact_url":"https://www.precisionmolding.com/contact/","products":[],"notes":"Tight-tolerance medical molding."},
      {"company_name":"Mondor","website_url":"https://www.mondor.com","contact_url":"https://www.mondor.com/en/contact","products":["Performance tights"],"notes":"Quebec leader in skating and dancewear."},
      {"company_name":"J.D. Irving","website_url":"https://www.jdirving.com","contact_url":"https://www.jdirving.com/contact-us","products":[],"notes":"Vertically integrated Maritimes giant."},
      {"company_name":"Access Labels","website_url":"https://www.accesslabels.ca","contact_url":"https://www.accesslabels.ca/contact/","products":["Industrial labels"],"notes":"Largest label maker in Atlantic Canada."},
      {"company_name":"Italpasta Limited","website_url":"https://www.italpasta.com","contact_url":"https://www.italpasta.com/contact-us/","products":["Pasta"],"notes":"Uses 100% Canadian durum wheat."},
      {"company_name":"Canada Mold Technology Inc.","website_url":"https://www.canadamold.com","contact_url":"https://canadamold.com/contact-us/","products":["Custom molds"],"notes":"High-capacity automotive toolmaker."},
      {"company_name":"Viberg Boot","website_url":"https://www.viberg.com","contact_url":"https://viberg.com/pages/contact","products":["Leather boots"],"notes":"High-end footwear manufacturer."},
      {"company_name":"Tolko Industries","website_url":"https://www.tolko.com","contact_url":"https://tolko.com/contact/","products":[],"notes":"Family-owned forest products leader."},
      {"company_name":"Label Design Ltd.","website_url":"https://www.labeldesign.ca","contact_url":"https://www.labeldesign.ca/contact/","products":["Apparel stickers"],"notes":"Pressure-sensitive label specialist."},
      {"company_name":"Arva Flour Mill","website_url":"https://www.arvaflourmill.com","contact_url":"https://www.arvaflourmill.com/pages/contact-us","products":[],"notes":"North America's oldest water mill."},
      {"company_name":"Plascon Plastics","website_url":"https://www.plasconplastics.com","contact_url":"https://plasconplastics.com/contact/","products":[],"notes":"Leader in waste-stream plastic molding."},
      {"company_name":"Quartz Co.","website_url":"https://www.quartz-co.com","contact_url":"https://quartz-co.com/en/pages/contact-us","products":[],"notes":"Sustainable luxury outerwear maker."},
      {"company_name":"Gorman Bros. Lumber","website_url":"https://www.gormanbros.com","contact_url":"https://www.gormanbros.com/contact-us/","products":["Finishing lumber"],"notes":"Premier lumberyard in Kelowna."},
      {"company_name":"Accu-Label","website_url":"https://www.accu-label.com","contact_url":"https://accu-label.com/contact-us/","products":["Fruit labels"],"notes":"Eco-friendly agricultural labeling."},
      {"company_name":"Rogers Foods","website_url":"https://www.rogersfoods.com","contact_url":"https://www.rogersfoods.com/contact-us/","products":["Cereal","Flour"],"notes":"High-quality milling in Western Canada."},
      {"company_name":"Scepter Corporation","website_url":"https://www.scepter.com","contact_url":"https://www.scepter.com/contact-us/","products":["Fuel containers"],"notes":"Global leader in rugged liquid storage."},
      {"company_name":"Tricots Maxime","website_url":"https://www.tricotsmaxime.com","contact_url":"https://www.tricotsmaxime.com/en/contact-us","products":["Knitted fabrics"],"notes":"Large Montreal circular knitting mill."},
      {"company_name":"Carrier Lumber","website_url":"https://www.carrierlumber.bc.ca","contact_url":"https://www.carrierlumber.bc.ca/contact/","products":[],"notes":"Innovator in sawmill modular design."},
      {"company_name":"DuraFast Label","website_url":"https://www.durafastlabel.com","contact_url":"https://www.durafastlabel.com/contact-us/","products":["In-house label printers"],"notes":"Supports DIY labeling solutions."},
      {"company_name":"Sun-Rype Products","website_url":"https://www.sunrype.com","contact_url":"https://www.sunrype.com/contact-us/","products":["Fruit juice"],"notes":"Major BC fruit processor."},
      {"company_name":"IPEX Inc.","website_url":"https://www.ipexna.com","contact_url":"https://www.ipexna.com/en-ca/contact-us/","products":[],"notes":"Supplier for industrial infrastructure."},
      {"company_name":"Kamik","website_url":"https://www.kamik.com","contact_url":"https://www.kamik.com/en-ca/pages/contact-us","products":["Outdoor boots"],"notes":"Sustainable footwear manufacturer."},
      {"company_name":"Dunkley Lumber","website_url":"https://www.dunkleylumber.com","contact_url":"https://dunkleylumber.com/contact-us/","products":["Foothills pine"],"notes":"Major sawmill operator in Western Canada."},
      {"company_name":"Affix Label & Print","website_url":"https://www.affixlabel.com","contact_url":"https://affixlabel.com/contact-us/","products":["Promotional print"],"notes":"Full-cycle print and label provider."},
      {"company_name":"Burnbrae Farms","website_url":"https://www.burnbraefarms.com","contact_url":"https://www.burnbraefarms.com/en/contact-us/","products":["Liquid eggs"],"notes":"Largest egg processor in Canada."},
      {"company_name":"Alte-Rego Corporation","website_url":"https://www.alte-rego.com","contact_url":"https://www.alte-rego.com/contact/","products":["Industrial packaging"],"notes":"Focus on high-performance films."},
      {"company_name":"Peerless Clothing","website_url":"https://www.peerless-clothing.com","contact_url":"https://www.peerless-clothing.com/contact","products":[],"notes":"Major garment manufacturer in Montreal."},
      {"company_name":"Kalesnikoff Lumber","website_url":"https://www.kalesnikoff.com","contact_url":"https://www.kalesnikoff.com/contact/","products":["Mass timber"],"notes":"Leader in CLT and Glulam production."},
      {"company_name":"LabTAG","website_url":"https://www.labtag.com","contact_url":"https://www.labtag.com/contact-us/","products":["Medical labels"],"notes":"Specialist in chemical-resistant labeling."},
      {"company_name":"Agropur","website_url":"https://www.agropur.com","contact_url":"https://www.agropur.com/en/contact-us","products":[],"notes":"Farmer-owned dairy cooperative."},
      {"company_name":"Royal Mat Inc.","website_url":"https://www.royalmat.com","contact_url":"https://www.royalmat.com/en/contact-us","products":[],"notes":"Processes waste tires into mats."},
      {"company_name":"House of Blanks","website_url":"https://www.houseofblanks.com","contact_url":"https://www.houseofblanks.com/pages/contact","products":[],"notes":"High-quality apparel made in Ontario."},
      {"company_name":"Timber Tiles","website_url":"https://www.timbertiles.ca","contact_url":"https://timbertiles.ca/contact/","products":[],"notes":"Value-added hemlock manufacturer."},
      {"company_name":"Mitchell Press","website_url":"https://www.mitchellpress.com","contact_url":"https://mitchellpress.com/contact/","products":["Commercial print"],"notes":"Large-format magazine printer."},
      {"company_name":"High Liner Foods","website_url":"https://www.highlinerfoods.com","contact_url":"https://www.highlinerfoods.com/contact-us/","products":["Frozen seafood"],"notes":"Leading frozen seafood processor."},
      {"company_name":"Pro-Flex Rubber","website_url":"https://www.proflex.ca","contact_url":"https://proflex.ca/en/contact-us/","products":["Hockey pucks"],"notes":"Specialist in railway and sports rubber."},
      {"company_name":"Samuelsohn","website_url":"https://www.samuelsohn.com","contact_url":"https://samuelsohn.com/pages/contact-us","products":["Luxury suits"],"notes":"Montreal-based high-end tailoring."},
      {"company_name":"Daizen Joinery","website_url":"https://www.daizen.com","contact_url":"https://daizen.com/contact/","products":[],"notes":"Precision CNC wood joinery."},
      {"company_name":"Hemlock Printers","website_url":"https://www.hemlock.com","contact_url":"https://www.hemlock.com/contact","products":[],"notes":"Industry leader in environmental print."},
      {"company_name":"E.D. Smith","website_url":"https://www.edsmith.com","contact_url":"https://www.edsmith.com/contact-us/","products":["Fruit jams"],"notes":"Historic condiment manufacturer."},
      {"company_name":"Kemflo Canada","website_url":"https://www.kemflocanada.com","contact_url":"https://kemflocanada.com/contact-us/","products":[],"notes":"Integrated OEM plastic molder."},
      {"company_name":"Canada Sportswear","website_url":"https://www.canadasportswear.com","contact_url":"https://www.canadasportswear.com/contact","products":["Corporate apparel"],"notes":"Major uniform and team supplier."},
      {"company_name":"BC Passive House","website_url":"https://www.bcpassivehouse.com","contact_url":"https://bcpassivehouse.com/contact/","products":["Prefab walls"],"notes":"High-performance building systems."},
      {"company_name":"Cober Solutions","website_url":"https://www.cober.com","contact_url":"https://cober.com/contact/","products":[],"notes":"Data-driven personalized print house."},
      {"company_name":"Kicking Horse Coffee","website_url":"https://www.kickinghorsecoffee.com","contact_url":"https://www.kickinghorsecoffee.com/contact-us/","products":[],"notes":"Fairtrade and organic coffee roaster."},
      {"company_name":"Performance Plastics Ltd.","website_url":"https://www.perplastics.com","contact_url":"https://www.perplastics.com/contact-us/","products":["Industrial molding"],"notes":"High-performance resin specialist."},
      {"company_name":"Bariatric Technologies","website_url":"https://www.bariatrictech.com","contact_url":"https://bariatrictech.com/contact/","products":["Medical textiles"],"notes":"Innovative specialized garment designer."},
      {"company_name":"EACOM Timber","website_url":"https://www.eacom.ca","contact_url":"https://eacom.ca/contact-us/","products":["I-joists","Lumber"],"notes":"Major Eastern Canadian lumber player."},
      {"company_name":"SinaLite","website_url":"https://www.sinalite.com","contact_url":"https://sinalite.com/en_ca/contact-us","products":[],"notes":"Trade printer for North America."},
      {"company_name":"Big Rock Brewery","website_url":"https://www.bigrockbeer.com","contact_url":"https://www.bigrockbeer.com/contact/","products":["Craft beer"],"notes":"Leading Canadian craft brewery."},
      {"company_name":"Capable Plastic Injection","website_url":"https://www.capableplastic.com","contact_url":"https://capableplastic.com/contact-us/","products":["Automotive trim"],"notes":"Precision small parts molder."},
      {"company_name":"Varitrim Textiles","website_url":"https://www.varitrim.com","contact_url":"https://www.varitrim.com/contact/","products":["Narrow fabrics"],"notes":"Apparel component manufacturer."},
      {"company_name":"Sinclar Group","website_url":"https://www.sinclar.com","contact_url":"https://www.sinclar.com/contact/","products":[],"notes":"Integrated wood producer in BC."},
      {"company_name":"Westkey Graphics","website_url":"https://www.westkeygraphics.com","contact_url":"https://www.westkeygraphics.com/contact/","products":[],"notes":"Operational and business print supplier."},
      {"company_name":"Clearly Canadian","website_url":"https://www.clearlycanadian.com","contact_url":"https://www.clearlycanadian.com/contact","products":[],"notes":"Premium beverage brand revival."},
      {"company_name":"Centennial Plastic Mfg.","website_url":"https://www.centennialplastic.com","contact_url":"https://centennialplastic.com/contact/","products":[],"notes":"Precision components for medical."},
      {"company_name":"Robocuts Textiles","website_url":"https://www.robocuts.com","contact_url":"https://robocuts.com/contact","products":["Automated cutting"],"notes":"CAD/CAM services for garment makers."},
      {"company_name":"Acadian Timber","website_url":"https://www.acadiantimber.com","contact_url":"https://www.acadiantimber.com/contact-us/","products":[],"notes":"Large timberland operator in NB."},
      {"company_name":"Ampco Manufacturers","website_url":"https://www.ampcomanufacturers.com","contact_url":"https://ampcomanufacturers.com/contact-us/","products":["Graphic overlays"],"notes":"Electronics and graphics manufacturer."},
      {"company_name":"Earth's Own","website_url":"https://www.earthsown.com","contact_url":"https://www.earthsown.com/contact-us/","products":["Oat milk"],"notes":"Plant-based dairy alternative leader."},
      {"company_name":"Polytainers Inc.","website_url":"https://www.polytainersinc.com","contact_url":"https://www.polytainersinc.com/contact/","products":[],"notes":"Thin-wall food container specialist."},
      {"company_name":"Manik Fashion","website_url":"https://www.manikfashion.com","contact_url":"https://www.manikfashion.com/contact","products":[],"notes":"Small-batch eco-apparel producer."},
      {"company_name":"Alberta Newsprint","website_url":"https://www.albertanewsprint.com","contact_url":"https://www.albertanewsprint.com/contact-us/","products":["Newsprint"],"notes":"High-quality paper mill in Alberta."},
      {"company_name":"Spicers Vancouver","website_url":"https://www.spicers.ca","contact_url":"https://www.spicers.ca/contact","products":["Printing supplies"],"notes":"Essential distributor for print shops."},
      {"company_name":"Ferrero Canada","website_url":"https://www.ferrero.ca","contact_url":"https://www.ferrero.ca/contact-us","products":["Chocolate"],"notes":"Major global chocolate hub in Ontario."},
      {"company_name":"Protoplast Inc.","website_url":"https://www.protoplast.com","contact_url":"https://www.protoplast.com/contact/","products":["Gas-assist molding"],"notes":"Advanced molding technology specialist."},
      {"company_name":"Marie Petit Maroquinerie","website_url":"https://www.mariepetit.ca","contact_url":"https://mariepetit.ca/contact","products":["Leather handbags"],"notes":"Specialized leather goods maker."},
      {"company_name":"Cascades","website_url":"https://www.cascades.com","contact_url":"https://www.cascades.com/en/contact-us","products":[],"notes":"Sustainability leader in packaging."},
      {"company_name":"Co-op Atlantic","website_url":"https://www.co-opatlantic.ca","contact_url":"https://co-opatlantic.ca/contact/","products":[],"notes":"Regional Maritime supply cooperative."},
      {"company_name":"Authentic Wine and Spirit","website_url":"https://www.awsm.ca","contact_url":"https://awsm.ca/contact/","products":[],"notes":"Distributor and brand manager."},
      {"company_name":"Papp Plastics","website_url":"https://www.pappplastics.com","contact_url":"https://www.pappplastics.com/contact/","products":["Chrome plastics"],"notes":"Automotive Tier 1 component supplier."},
      {"company_name":"Chateau Bodywear","website_url":"https://www.chateaubodywear.com","contact_url":"https://chateaubodywear.com/contact-us/","products":["Underwear"],"notes":"Large sleepwear wholesaler."},
      {"company_name":"Columbia Forest Products","website_url":"https://www.columbiaforestproducts.com","contact_url":"https://www.columbiaforestproducts.com/contact-us/","products":["Plywood veneer"],"notes":"Formaldehyde-free decorative wood."},
      {"company_name":"CCL Industries","website_url":"https://www.cclind.com","contact_url":"https://cclind.com/contact/","products":[],"notes":"Global leader in labeling technology."}
    ]
    $json$::jsonb
  ) as x(
    company_name text,
    website_url text,
    contact_url text,
    products text[],
    notes text
  )
)
insert into public.suppliers (
  name,
  website,
  contact_url,
  country,
  products,
  notes
)
select
  seed.company_name,
  seed.website_url,
  seed.contact_url,
  'Canada',
  coalesce(seed.products, '{}'::text[]),
  seed.notes
from seed
where not exists (
  select 1
  from public.suppliers existing
  where lower(existing.name) = lower(seed.company_name)
);
